
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.asodc.camel;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.10
 * Thu Feb 16 17:04:27 CET 2023
 * Generated source version: 2.2.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderEndpointService",
                      portName = "OrderService",
                      targetNamespace = "http://camel.asodc.com",
                      wsdlLocation = "file:/home/dafe/workspace/camel-patterns/cxf-contract-first-java/src/main/resources/wsdl/order.wsdl",
                      endpointInterface = "com.asodc.camel.OrderEndpoint")
                      
public class OrderEndpointImpl implements OrderEndpoint {

    private static final Logger LOG = Logger.getLogger(OrderEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see com.asodc.camel.OrderEndpoint#order(java.lang.String  partName ,)int  amount ,)java.lang.String  customerName )*
     */
    public java.lang.String order(java.lang.String partName,int amount,java.lang.String customerName) { 
        LOG.info("Executing operation order");
        System.out.println(partName);
        System.out.println(amount);
        System.out.println(customerName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
